apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: sample-config
    apps.open-cluster-management.io/reconcile-rate: medium
  name: sample-config-subscription
spec:
  channel: rhacm-demo/helmchart-repo
  name: sample-config
  packageOverrides:
  - packageName: sample-config
    packageAlias: rhacm-helm-demo
  packageFilter:
    version: "1.6.0"
  placement:
    placementRef:
      kind: PlacementRule
      name: all-openshift-clusters-placement-rule
