apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift-clusters-placement-rule
spec:
  clusterConditions: []
  clusterSelector:
    matchExpressions:
      - key: openshiftVersion
        operator: Exists
